[dig_ctrl]
raw_data_dirs = ["data/raw/atac+rna+adt/dogma/dig_ctrl"]
raw_data_frags = ["GSM5065530_DIG_CTRL_fragments.tsv.gz"]
combs = [[ ["atac", "adt"] ]]
comb_ratios = [[ 1 ]]
s_joint = [[ 0 ]]
train_ratio = 1
N = 256

[dig_stim]
raw_data_dirs = ["data/raw/atac+rna+adt/dogma/dig_stim"]
raw_data_frags = ["GSM5065533_DIG_STIM_fragments.tsv.gz"]
combs = [[ ["atac", "rna"] ]]
comb_ratios = [[ 1 ]]
s_joint = [[ 0 ]]
train_ratio = 1
N = 256

[lll_ctrl]
raw_data_dirs = ["data/raw/atac+rna+adt/dogma/lll_ctrl"]
raw_data_frags = ["GSM5065530_DIG_CTRL_fragments.tsv.gz"]
combs = [[ ["rna", "adt"] ]]
comb_ratios = [[ 1 ]]
s_joint = [[ 0 ]]
train_ratio = 1
N = 256

[lll_stim]
raw_data_dirs = ["data/raw/atac+rna+adt/dogma/lll_stim"]
raw_data_frags = ["GSM5065527_LLL_STIM_fragments.tsv.gz"]
combs = [[ ["atac", "rna", "adt"] ]]
comb_ratios = [[ 1 ]]
s_joint = [[ 0 ]]
train_ratio = 1
N = 256

[tea_W3]
raw_data_dirs = ["data/raw/atac+rna+adt/tea/TEA-seq/w3"]
raw_data_frags = ["GSM5123951_X066-MP0C1W3_leukopak_perm-cells_tea_200M_atac_filtered_fragments.tsv.gz"]
combs = [[ ["atac", "adt"] ]]
comb_ratios = [[ 1 ]]
s_joint = [[ 0 ]]
train_ratio = 1
N = 256

[tea_W4]
raw_data_dirs = ["data/raw/atac+rna+adt/tea/TEA-seq/w4"]
raw_data_frags = ["GSM5123952_X066-MP0C1W4_leukopak_perm-cells_tea_200M_atac_filtered_fragments.tsv.gz"]
combs = [[ ["atac", "rna"] ]]
comb_ratios = [[ 1 ]]
s_joint = [[ 0 ]]
train_ratio = 1
N = 256

[tea_W5]
raw_data_dirs = ["data/raw/atac+rna+adt/tea/TEA-seq/w5"]
raw_data_frags = ["GSM5123953_X066-MP0C1W5_leukopak_perm-cells_tea_200M_atac_filtered_fragments.tsv.gz"]
combs = [[ ["rna", "adt"] ]]
comb_ratios = [[ 1 ]]
s_joint = [[ 0 ]]
train_ratio = 1
N = 256

[tea_W6]
raw_data_dirs = ["data/raw/atac+rna+adt/tea/TEA-seq/w6"]
raw_data_frags = ["GSM5123954_X066-MP0C1W6_leukopak_perm-cells_tea_200M_atac_filtered_fragments.tsv.gz"]
combs = [[ ["atac", "rna", "adt"] ]]
comb_ratios = [[ 1 ]]
s_joint = [[ 0 ]]
train_ratio = 1
N = 256
